#!/bin/sh
# only need to run when merging from upstream

if [ ! -e src/openvpn/openvpn.c ]; then
    echo "Call me from external/openvpn/" >&2
    exit 1
fi

# yes, this checks for host headers/libs. run git diff config.h afterwards to check...
autoreconf -fvi
./configure --enable-password-save --enable-iproute2 --disable-pkcs11 --disable-selinux

{ awk -f configure_h.awk config.h && \
  awk -f configure_log.awk config.log
} > configure.h
